module.exports= {
	playback: [
	  '█{black-fg}···········{/black-fg}',
	  '▓█{black-fg}··········{/black-fg}',
	  '▒▓█{black-fg}·········{/black-fg}',
	  '░▒▓█{black-fg}········{/black-fg}',
	  '{black-fg}·{/black-fg}░▒▓{black-fg}···{/black-fg}█{black-fg}····{/black-fg}',
	  '{black-fg}··{/black-fg}░▒{black-fg}··{/black-fg}█▓{black-fg}····{/black-fg}',
	  '{black-fg}···{/black-fg}░{black-fg}·{/black-fg}█▓▒{black-fg}····{/black-fg}',
	  '{black-fg}····{/black-fg}█▓▒░{black-fg}····{/black-fg}',
	  '{black-fg}····{/black-fg}▓▒░{black-fg}·{/black-fg}█{black-fg}···{/black-fg}',
	  '{black-fg}····{/black-fg}▒░{black-fg}··{/black-fg}▓█{black-fg}··{/black-fg}',
	  '{black-fg}····{/black-fg}░{black-fg}···{/black-fg}▒▓█{black-fg}·{/black-fg}',
	  '{black-fg}········{/black-fg}░▒▓█',
	  '{black-fg}·········{/black-fg}░▒▓',
	  '{black-fg}··········{/black-fg}░▒',
	  '{black-fg}···········{/black-fg}░',
	  '{black-fg}············{/black-fg}',
	],
	duplicate: [
		'{green-fg}████████████{/green-fg}',
		'████████████',
		'████████▓▓▓▓',
		'████▓▓▓▓▒▒▒▒',
		'▓▓▓▓▒▒▒▒░░░░',
		'▒▒▒▒░░░░{black-fg}····{/black-fg}',
		'░░░░{black-fg}········{/black-fg}',
		'{black-fg}············{/black-fg}',
	],
	multiply: [
		'{red-fg}█··█·██·█··█{/red-fg}',
		'░··░·░░·░··░',
		'{red-fg}█··█·██·█··█{/red-fg}',
		'░··░·░░·░··░',
		'{red-fg}█··█·██·█··█{/red-fg}',
		'░··░·░░·░··░',
		'{black-fg}············{/black-fg}', 
	],
	trim: [
		'{yellow-fg}···█··█··█··{/yellow-fg}',
		'···░··░··░··',
		'{yellow-fg}█····█····█·{/yellow-fg}',
		'░····░·····░',
		'{yellow-fg}···█··█··█··{/yellow-fg}',
		'···░··░··░··',
		'{black-fg}············{/black-fg}',
	],
	clean: [
				'{blue-fg}████████████{/blue-fg}',
				'████████████',
				'▓▓▓▓████████',
				'▒▒▒▒▓▓▓▓████',
				'░░░░▒▒▒▒▓▓▓▓',
				'{black-fg}····{/black-fg}░░░░▒▒▒▒',
				'{black-fg}········{/black-fg}░░░░',
				'{black-fg}············{/black-fg}',
	],
	
	record: [
	  '█▓▒░',
	  '█▓▒░',
	  '█▓▒░',
	  '█▓▒░',
	  '▓█▓▒',
	  '▓█▓▒',
	  '▓█▓▒',
	  '▓█▓▒',
	  '▒▓█▓',
	  '▒▓█▓',
	  '▒▓█▓',
	  '▒▓█▓',
	  '░▒▓█',
	  '░▒▓█',
	  '░▒▓█',
	  '░▒▓█',
	  '▒░▒▓',
	  '▒░▒▓',
	  '▒░▒▓',
	  '▒░▒▓',
	  '▓▒░▒',
	  '▓▒░▒',
	  '▓▒░▒',
	  '▓▒░▒',
	]
}
